import type { Metadata } from "next";
import { Inter, Roboto_Mono, Fira_Code } from "next/font/google";
import { ReduxProvider } from "../redux/Provider";
import "./globals.css";

// Main sans-serif font (Inter is highly readable and modern)
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
  weight: ["400", "500", "600", "700"],
});

// Monospace font option 1 (clean and professional)
const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto-mono",
  weight: ["400", "500", "600"],
});

// Monospace font option 2 (great for code, with ligatures)
const firaCode = Fira_Code({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-fira-code",
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  icons: "/1-nobg.png",
  title: "Zivuko Online E-commerce Platform",
  description: "Generated by create next app",
  // Recommended to add these for better SEO
  metadataBase: new URL("https://your-production-url.com"), // Replace with your actual URL
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${robotoMono.variable}`}>
      {/* Or use firaCode instead of robotoMono if you prefer: */}
      {/* <html lang="en" className={`${inter.variable} ${firaCode.variable}`}> */}
      <body className="antialiased">
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}